### ISSUE TITLE
We should show the release version after net options

### ISSUE THREAD

**Issue by fanlong** [Conflux-Chain/conflux-scan#157]
Something like Conflux Pontus (v0.5.0 a432.....)
Conflux Testnet (v0.5.1-alpha-1 48fc...)

**Do you want to request a *feature* or report a *bug*?**

Request a feature.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

When we have multiple nets being public (main/test), users will get confused on which version to use.

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by AngeliaQ** [comment]
Do you mean the fullnode version?

**Comment by lionking062** [comment]
If the version info refers to fullnode version, I suggest we mention it in notice box which was shown in green frame in the picture below. 

![image](https://user-images.githubusercontent.com/43574192/80445012-ce976b00-8945-11ea-9e98-59964dfd7055.png)

**Comment by fanlong** [comment]
Yes. I agree with @lionking062 . That's what I meant. Consider to put versions in the notice box

**Comment by AngeliaQ** [comment]
> Yes. I agree with @lionking062 . That's what I meant. Consider to put versions in the notice box

OK, We will get the version from core team and deal with the issue
