### ISSUE TITLE
Bottom banner issue summary

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-scan#2]
![image](https://user-images.githubusercontent.com/35757521/55373868-1f694400-5539-11e9-89a2-f4c55ae5f081.png)

**Comment by zhaoyannian** [comment]
Label设计如此。多语言切换正在看，

**Comment by AngeliaQ** [comment]
目前中英文切换只保留了上面的按钮，把下面的去掉了，想放个跳转官网的按钮，目前小贝还在设计，右边三个按钮可以跳转了，换成Twitter，github，medium
