### ISSUE TITLE
Add ability to jump to any page

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/conflux-scan#216]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Under [confluxscan.io/blocks](https://confluxscan.io/blocks), I have to go through the list of blocks page by page.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Would be nice to have something like `confluxscan.io/blocks?page=100` to jump to a page instantly.

Currently, I'm looking for blocks with many transactions. Recently, TPS is 0, but I recall a few days back there were some blocks with many transactions. Of course, I can look for them using RPC but it would be more convenient to just search through the block list.

**Comment by Thegaram** [comment]
Etherscan has this: [etherscan.io/blocks?p=3](https://etherscan.io/blocks?p=3).

**Comment by AngeliaQ** [comment]
The feature will be added in v2.0. We are working on it, and it will be deployed in the middle of October

**Comment by Thegaram** [comment]
Fixed in the latest release.
