### ISSUE TITLE
Invalid addresses should not show an account page

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/conflux-scan#221]
**Do you want to request a *feature* or report a *bug*?**

Bug (-ish).

**What is the current behavior?**

If I search for `0x6651566eed99ab3dd1ee2fea28a76c3ee2fd3946 ` (which is an Ethereum address), I see a normal account page.

Btw, it's also weird, because it shows tokens but no transactions:

![image](https://user-images.githubusercontent.com/7571518/94238591-e5e87d80-ff10-11ea-83f3-e4f72581fc8a.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

https://confluxscan.io/address/0x6651566eed99ab3dd1ee2fea28a76c3ee2fd3946

**What is the expected behavior?**

For addresses that are obviously invalid (i.e. do not start with `1` or `8`), Scan should show an error. E.g. `"Invalid address"` or `"This does not seem to be a valid Conflux address"`.

**Comment by AngeliaQ** [comment]
we will deal with the problem in next version(breaking change with v2.0.0).
If the address starts with '0x0' or '0x8', it will jump to contract page, 
and if the address starts with '0x1' , it will jump to address page
otherwise, it will jump to 404 page

**Comment by Thegaram** [comment]
Nice!

> otherwise, it will jump to 404 page

If it's a valid-looking address (i.e. 20-byte long) but starts with `2-7` or `9-f`, I would suggest we provide some hint, not just a plain 404. E.g. `"Account not found. Conflux addresses start with 0x0 (built-in contracts), 0x1 (user accounts), 0x8 (smart contracts)"`.

**Comment by Thegaram** [comment]
Fixed in the new version.
