### ISSUE TITLE
Chinese lang issues

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-scan#3]
![image](https://user-images.githubusercontent.com/35757521/55374062-c6e67680-5539-11e9-91c8-15b3810e96d5.png)

![image](https://user-images.githubusercontent.com/35757521/55374196-2b093a80-553a-11e9-8929-eb1a1dc240f1.png)

![image](https://user-images.githubusercontent.com/35757521/55374162-1331b680-553a-11e9-821c-5a01b1a5b06c.png)

![image](https://user-images.githubusercontent.com/35757521/55374304-8e936800-553a-11e9-9ba2-d75514fde0ee.png)

![image](https://user-images.githubusercontent.com/35757521/55374399-e29e4c80-553a-11e9-9521-d0ad258a785a.png)

**Comment by AngeliaQ** [comment]
Epoch暂时先不改
