### ISSUE TITLE
Block information page issues

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-scan#5]
![image](https://user-images.githubusercontent.com/35757521/55374734-1f1e7800-553c-11e9-8de7-3e3e37d48319.png)

![image](https://user-images.githubusercontent.com/35757521/55375010-1bd7bc00-553d-11e9-965d-d50d3e15cd51.png)

**Comment by zhaoyannian** [comment]
resolve

**Comment by AngeliaQ** [comment]
返回跳转功能有专门issue，第一个问题已解决
