### ISSUE TITLE
Account information page issues

### ISSUE THREAD

**Issue by boqiu** [Conflux-Chain/conflux-scan#9]
![image](https://user-images.githubusercontent.com/35757521/55375654-999cc700-553f-11e9-8e76-ed65748472dd.png)

![image](https://user-images.githubusercontent.com/35757521/55375689-b5a06880-553f-11e9-8c58-a1ef2f4c4fca.png)

![image](https://user-images.githubusercontent.com/35757521/55375788-044e0280-5540-11e9-889d-db92eae2a665.png)

**Comment by zhaoyannian** [comment]
resolve
